on: push
name: Build and deploy to gh-pages
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@e7aaefe
      with:
        args: install
    - name: Build
      uses: actions/npm@e7aaefe
      with:
        args: run build
    - name: Deploy
      uses: nchaulet/github-action-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLIC_PATH: build
